### ISSUE TITLE
WildFly not able to deploy war file

### ISSUE THREAD

**Issue by sarvan2research** [phillip-kruger/jello#1]
Hi,

When am trying to deploy using wildfly its failing with below error.Could you please assist in resolving below issue.

Caused by: java.lang.NoClassDefFoundError: Ljavax/security/enterprise/SecurityContext;
        at java.lang.Class.getDeclaredFields0(Native Method) [rt.jar:1.8.0_221]
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583) [rt.jar:1.8.0_221]
        at java.lang.Class.getDeclaredFields(Class.java:1916) [rt.jar:1.8.0_221]
        at org.jboss.as.server.deployment.reflect.ClassReflectionIndex.<init>(ClassReflectionIndex.java:57) [wildfly-server-8.1.0.Final.jar:8.1.0.Final]
        at org.jboss.as.server.deployment.reflect.DeploymentReflectionIndex.getClassIndex(DeploymentReflectionIndex.java:68) [wildfly-server-8.1.0.Final.jar:8.1.0.Final]
        ... 10 more
Caused by: java.lang.ClassNotFoundException: javax.security.enterprise.SecurityContext from [Module "deployment.cards.war:main" from Service Module Loader]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:213) [jboss-modules.jar:1.3.3.Final]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:459) [jboss-modules.jar:1.3.3.Final]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:408) [jboss-modules.jar:1.3.3.Final]
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:389) [jboss-modules.jar:1.3.3.Final]
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:134) [jboss-modules.jar:1.3.3.Final]
        ... 15 more

16:15:27,546 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 3) JBAS014613: Operation ("add") failed - address: ([("deployment" => "cards.war")]) - failure description: {"JBAS014671: Failed services" => {"jboss.deployment.unit.\"cards.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"cards.war\".POST_MODULE: JBAS018733: Failed to process phase POST_MODULE of deployment \"cards.war\"
    Caused by: java.lang.RuntimeException: JBAS018757: Error getting reflective information for class com.github.phillipkruger.jello.queue.CardQueueProducer with ClassLoader ModuleClassLoader for Module \"deployment.cards.war:main\" from Service Module Loader
    Caused by: java.lang.NoClassDefFoundError: Ljavax/security/enterprise/SecurityContext;
    Caused by: java.lang.ClassNotFoundException: javax.security.enterprise.SecurityContext from [Module \"deployment.cards.war:main\" from Service Module Loader]"}}
16:15:27,556 ERROR [org.jboss.as.server] (management-handler-thread - 3) JBAS015870: Deploy of deployment "cards.war" was rolled back with the following failure message:
{"JBAS014671: Failed services" => {"jboss.deployment.unit.\"cards.war\".POST_MODULE" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"cards.war\".POST_MODULE: JBAS018733: Failed to process phase POST_MODULE of deployment \"cards.war\"
    Caused by: java.lang.RuntimeException: JBAS018757: Error getting reflective information for class com.github.phillipkruger.jello.queue.CardQueueProducer with ClassLoader ModuleClassLoader for Module \"deployment.cards.war:main\" from Service Module Loader
    Caused by: java.lang.NoClassDefFoundError: Ljavax/security/enterprise/SecurityContext;
    Caused by: java.lang.ClassNotFoundException: javax.security.enterprise.SecurityContext from [Module \"deployment.cards.war:main\" from Service Module Loader]"}}

Thanks,
Saravanakumar R

**Comment by phillip-kruger** [comment]
Hi
What version of maven are you using ?

**Comment by sarvan2research** [comment]
Hi,

Am using apache-maven-3.6.1.Does it relate to maven version?

**Comment by phillip-kruger** [comment]
Not sure. Just checking. And your Java version ?

**Comment by sarvan2research** [comment]
Java version 1.8.0_221

**Comment by sarvan2research** [comment]
Issue due to wildfly version downloaded as 8.01  instead of latest 17.0.1.Changed version to 17.0.1 issue sorted out.

Thanks

**Comment by phillip-kruger** [comment]
Ok cool. The maven plugin should have downloaded the latest ?
